refactor: page header component
jembi/jempi-web pull request #18
Opened 2023-01-09 16:05 UTC by IlyesBenAmara

This PR is a refactor of the page header component used in multiple screens

2023-01-10 17:44 UTC, marrouchi requested changes
Looks good ! Just a couple of minor changes.

2023-01-10 17:44 UTC, marrouchi commented on src/components/shell/PageHeader.tsx
> +  buttonComponents?: JSX.Element[]
```suggestion
  buttons?: JSX.Element[]
```

2023-01-10 17:44 UTC, marrouchi commented on src/components/shell/PageHeader.tsx
> +          {buttonComponents?.map(elem => (
```suggestion
          {buttonComponents?.map(button => (
```

2023-01-11 17:08 UTC, marrouchi approved these changes

2023-01-12 13:18 UTC, Lumiere-Lodi reviewed
LGTM

2023-01-12 13:19 UTC, merged