fix: mock backend environment variable
jembi/jempi-web pull request #29
Opened 2023-01-20 16:47 UTC by IlyesBenAmara

This PR fixes the problem for enabling or disabling the mock backend

2023-01-20 17:31 UTC, marrouchi requested changes

2023-01-20 17:31 UTC, marrouchi commented on src/config.ts
> +    process.env.REACT_APP_MOCK_BACKEND === 'true' ? true : false || false,
```suggestion
    process.env.REACT_APP_MOCK_BACKEND === 'true',
```

2023-01-23 07:58 UTC, Lumiere-Lodi approved these changes
Good. Looks good

2023-01-23 09:52 UTC, marrouchi approved these changes

2023-01-23 09:52 UTC, merged