fix: navigation to linked records screen
jembi/jempi-web pull request #41
Opened 2023-02-08 15:45 UTC by IlyesBenAmara

- this PR fixes the issue on the linked record screen

2023-02-08 16:15 UTC, marrouchi requested changes

2023-02-08 16:15 UTC, marrouchi commented on src/components/linkedRecords/LinkedRecords.tsx
> +  console.log(uid)
```suggestion
  console.log(uid)
```
Please remove this

2023-02-08 16:15 UTC, marrouchi commented on src/services/mockBackend.ts
> +      console.log(config)
This as well :pray:

2023-02-08 16:20 UTC, IlyesBenAmara commented on src/components/linkedRecords/LinkedRecords.tsx
> +  console.log(uid)
my bad :sweat_smile:

2023-02-09 10:52 UTC, marrouchi approved these changes

2023-02-09 16:25 UTC, IlyesBenAmara commented
I added integration changes so that we could display the linked records. @MatthewErispe @Lumiere-Lodi @marrouchi let me know what you think guys ;)

2023-02-10 10:00 UTC, marrouchi requested changes

2023-02-10 12:43 UTC, marrouchi approved these changes

2023-02-10 13:46 UTC, Lumiere-Lodi approved these changes
Looks good to me. At this point since we haven't updated the mockData for golden search result it will only work with the actual API and not the mock API. However, all is good.

2023-02-10 14:50 UTC, MatthewErispe approved these changes
LGTM

2023-02-10 14:50 UTC, merged