fix ui in notification screen
jembi/jempi-web pull request #58
Opened 2023-03-06 16:11 UTC by IlyesBenAmara

- this PR adds the UI corrections to the notifications screen

2023-03-07 08:41 UTC, MatthewErispe reviewed
@IlyesBenAmara is it possilble to add some unit tests for the notifications worklist?

2023-03-07 08:41 UTC, MatthewErispe commented on src/components/reviewMatches/NotificationWorklist.tsx
> +      params.value ? moment(params.value).format('DD/MM/YYYY') : null
```suggestion
      params.value ? moment.unix(params.value).format('DD/MM/YYYY') : null
```

2023-03-07 08:41 UTC, MatthewErispe commented on src/components/reviewMatches/NotificationWorklist.tsx
> +      params.value ? moment(params.value).format('DD/MM/YYYY') : null
@IlyesBenAmara I think the value is a timestamp and needs the unix to convert ot date

2023-03-07 11:35 UTC, MatthewErispe requested changes
@IlyesBenAmara are you able to add some unit tests for the notification worklist?

2023-03-15 07:20 UTC, marrouchi requested changes

2023-03-15 07:20 UTC, marrouchi commented on src/components/reviewMatches/NotificationWorklist.tsx
> +      params.value ? moment.unix(params.value).format('DD/MM/YYYY') : null
Would be better to transform any string to Date object at the fetch function level.
Then we could add a helper function to format any date, so we keen consistent format across the screens.

2023-03-16 13:56 UTC, marrouchi requested changes

2023-03-16 13:56 UTC, marrouchi commented on src/utils/formatters.ts
> +    return moment(value).format('DD/MM/YYYY')
Could we add a else condition ?

2023-03-16 13:56 UTC, marrouchi commented on src/utils/formatters.ts
>  export const formatDate = (value: unknown) => {
Let's define the type here "Date"

2023-03-16 13:56 UTC, marrouchi commented on src/types/Notification.ts
> +  created: string | Date
```suggestion
  created: Date
```
Let's be strict about the type.

2023-03-17 07:37 UTC, MatthewErispe approved these changes

2023-03-17 07:47 UTC, merged